// @vitest-environment node
import { describe, it, expect } from 'vitest';
import request from 'supertest';
import jwt from 'jsonwebtoken';
import { createApp } from '../src/server/app';
import { createInvitationService } from '../src/server/services/invitationService';
import { createQuoteService } from '../src/server/services/quoteService';
import { createAuditService } from '../src/server/services/auditService';
import { createInMemoryInvitationRepository } from '../src/server/db/inMemoryInvitationRepository';
import { createInMemoryQuoteRepository } from '../src/server/db/inMemoryQuoteRepository';
import { createInMemoryAuditRepository } from '../src/server/db/inMemoryAuditRepository';

const CLIENT_SECRET = 'test-client-secret-minimum-32-chars-long!!';
const TENANT_ACCOUNT_ID = 9999;
const OTHER_TENANT_ACCOUNT_ID = 8888;

function makeApp() {
  const invRepo = createInMemoryInvitationRepository();
  const quoteRepo = createInMemoryQuoteRepository();
  const auditRepo = createInMemoryAuditRepository();
  const invService = createInvitationService(invRepo, auditRepo);
  const quoteService = createQuoteService(quoteRepo, auditRepo);
  const auditService = createAuditService(auditRepo);
  const app = createApp(invService, quoteService, CLIENT_SECRET, undefined, undefined, undefined, undefined, undefined, undefined, auditService);
  return { app, invService };
}

function buyerToken(accountId = TENANT_ACCOUNT_ID) {
  return jwt.sign({ dat: { account_id: accountId, user_id: 42, short_lived_token: 'slt' } }, CLIENT_SECRET, { expiresIn: '1h' });
}

describe('Audit routes', () => {
  it('requires auth', async () => {
    const { app } = makeApp();
    const res = await request(app).get('/api/buyer/audit');
    expect(res.status).toBe(401);
  });

  it('returns audit events generated by real invitation actions', async () => {
    const { app, invService } = makeApp();
    await invService.create(`monday-account-${TENANT_ACCOUNT_ID}`, {
      eventId: 'event-1', eventReference: 'RFQ-1', eventTitleSnapshot: 'RFQ 1',
      supplierId: 'sup-1', supplierNameSnapshot: 'Acme', supplierEmailSnapshot: 'a@acme.com',
    }, '42');

    const res = await request(app).get('/api/buyer/audit').set('Authorization', `Bearer ${buyerToken()}`);
    expect(res.status).toBe(200);
    expect(res.body.events).toHaveLength(1);
    expect(res.body.events[0].action).toBe('INVITATION_CREATED');
    expect(res.body.events[0].eventId).toBe('event-1');
  });

  it('filters by eventId query param', async () => {
    const { app, invService } = makeApp();
    const tenantId = `monday-account-${TENANT_ACCOUNT_ID}`;
    await invService.create(tenantId, { eventId: 'event-1', eventReference: 'RFQ-1', eventTitleSnapshot: 'RFQ 1', supplierId: 'sup-1', supplierNameSnapshot: 'Acme', supplierEmailSnapshot: 'a@acme.com' }, '42');
    await invService.create(tenantId, { eventId: 'event-2', eventReference: 'RFQ-2', eventTitleSnapshot: 'RFQ 2', supplierId: 'sup-2', supplierNameSnapshot: 'Beta', supplierEmailSnapshot: 'b@beta.com' }, '42');

    const res = await request(app).get('/api/buyer/audit?eventId=event-1').set('Authorization', `Bearer ${buyerToken()}`);
    expect(res.body.events).toHaveLength(1);
    expect(res.body.events[0].eventId).toBe('event-1');
  });

  it('never returns another tenant\'s audit events', async () => {
    const { app, invService } = makeApp();
    await invService.create(`monday-account-${TENANT_ACCOUNT_ID}`, {
      eventId: 'event-1', eventReference: 'RFQ-1', eventTitleSnapshot: 'RFQ 1', supplierId: 'sup-1', supplierNameSnapshot: 'Acme', supplierEmailSnapshot: 'a@acme.com',
    }, '42');

    const res = await request(app).get('/api/buyer/audit').set('Authorization', `Bearer ${buyerToken(OTHER_TENANT_ACCOUNT_ID)}`);
    expect(res.body.events).toHaveLength(0);
  });

  it('exports a CSV file', async () => {
    const { app, invService } = makeApp();
    await invService.create(`monday-account-${TENANT_ACCOUNT_ID}`, {
      eventId: 'event-1', eventReference: 'RFQ-1', eventTitleSnapshot: 'RFQ 1', supplierId: 'sup-1', supplierNameSnapshot: 'Acme', supplierEmailSnapshot: 'a@acme.com',
    }, '42');

    const res = await request(app).get('/api/buyer/audit/export.csv').set('Authorization', `Bearer ${buyerToken()}`);
    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toContain('text/csv');
    expect(res.text.split('\n')[0]).toBe('timestamp,action,entityType,entityId,eventId,actorType,actorId,metadata');
  });
});
