import type { Supplier } from '../../shared/types/domain';

const tenantId = 'ariavel-development-tenant';
const timestamp = '2026-09-01T09:00:00.000Z';

export const mockSuppliers: Supplier[] = [
  { id: 'supplier-1', tenantId, name: 'Acme Materials', supplierCode: 'AC-100', status: 'ACTIVE', category: 'Raw Materials', country: 'Germany', primaryContactName: 'Maya Patel', email: 'sales@acme.example', phone: '+49 30 555 0101', currency: 'EUR', paymentTerms: '30 days', defaultIncoterm: 'DAP', preferred: true, rating: 4, notes: 'Primary metals and engineered materials partner.', sourceType: 'ARIAVEL', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-2', tenantId, name: 'NorthStar Packaging', supplierCode: 'NS-220', status: 'ACTIVE', category: 'Packaging', country: 'Bulgaria', primaryContactName: 'Elena Petrova', email: 'quotes@northstar.example', phone: '+359 2 555 0102', currency: 'EUR', paymentTerms: '60 days', defaultIncoterm: 'FCA', preferred: true, rating: 5, sourceType: 'MONDAY_BOARD', mondayBoardId: 'mock-board-suppliers', mondayItemId: 'mock-item-2', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-3', tenantId, name: 'BlueRoute Logistics', supplierCode: 'BR-041', status: 'INACTIVE', category: 'Logistics', country: 'Greece', primaryContactName: 'Nikos Damianou', email: 'tenders@blueroute.example', currency: 'EUR', paymentTerms: '45 days', preferred: false, rating: 3, sourceType: 'IMPORT', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-4', tenantId, name: 'Vertex Equipment', supplierCode: 'VE-310', status: 'ACTIVE', category: 'Equipment', country: 'Netherlands', primaryContactName: 'Sofia de Vries', email: 'orders@vertex.example', currency: 'EUR', paymentTerms: '30 days', defaultIncoterm: 'EXW', preferred: false, rating: 4, sourceType: 'ARIAVEL', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-5', tenantId, name: 'Lumen Facility Services', supplierCode: 'LF-087', status: 'PENDING', category: 'Services', country: 'France', primaryContactName: 'Camille Laurent', email: 'procurement@lumen.example', currency: 'EUR', preferred: false, sourceType: 'ARIAVEL', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-6', tenantId, name: 'Oakline Components', supplierCode: 'OC-514', status: 'BLOCKED', category: 'Raw Materials', country: 'United Kingdom', primaryContactName: 'Daniel Reed', email: 'commercial@oakline.example', currency: 'GBP', paymentTerms: 'Prepayment', preferred: false, rating: 2, notes: 'Blocked pending compliance review.', sourceType: 'ARIAVEL', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-7', tenantId, name: 'Pinnacle Printworks', status: 'PENDING', category: 'Packaging', country: 'Poland', email: 'hello@pinnacle.example', currency: 'EUR', preferred: false, sourceType: 'ARIAVEL', createdAt: timestamp, updatedAt: timestamp },
  { id: 'supplier-8', tenantId, name: 'TerraLine Freight', supplierCode: 'TF-118', status: 'ACTIVE', category: 'Logistics', country: 'Spain', primaryContactName: 'Lucía Ramos', email: 'rates@terraline.example', currency: 'EUR', paymentTerms: '60 days', defaultIncoterm: 'FCA', preferred: true, rating: 4, sourceType: 'MONDAY_BOARD', mondayBoardId: 'mock-board-suppliers', mondayItemId: 'mock-item-8', createdAt: timestamp, updatedAt: timestamp },
];
