import type { SourcingEvent } from '../../shared/types/domain';

// M4 mock sourcing events for local development — replaces M1 placeholder mock
export const mockSourcingEvents: SourcingEvent[] = [
  {
    id: 'rfq-mock-1',
    tenantId: 'ariavel-development-tenant',
    reference: 'RFQ-2026-A7K3',
    title: 'Q3 Packaging Materials',
    status: 'DRAFT',
    currency: 'EUR',
    deadline: '2026-09-25',
    category: 'Packaging',
    ownerUserId: 'dev-user',
    ownerName: 'Dev User',
    lines: [
      { id: 'line-1a', description: 'Corrugated boxes 60×40×30cm', quantity: 5000, unit: 'pcs', sku: 'BOX-6040' },
      { id: 'line-1b', description: 'Bubble wrap rolls 50cm', quantity: 200, unit: 'm', targetUnitPrice: 1.2 },
    ],
    supplierSelections: [
      { supplierId: 'sup-1', source: 'ARIAVEL', supplierNameSnapshot: 'Acme Packaging', supplierCodeSnapshot: 'ACP-001', emailSnapshot: 'sales@acmepkg.com', selectedAt: '2026-09-01T10:00:00Z' },
    ],
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
    createdByUserId: 'dev-user',
    updatedByUserId: 'dev-user',
  },
  {
    id: 'rfq-mock-2',
    tenantId: 'ariavel-development-tenant',
    reference: 'RFQ-2026-B9M1',
    title: 'Warehouse Safety Equipment',
    status: 'READY_FOR_INVITATION',
    currency: 'EUR',
    deadline: '2026-09-30',
    category: 'Safety',
    ownerUserId: 'dev-user',
    ownerName: 'Dev User',
    lines: [
      { id: 'line-2a', description: 'Safety helmets EN397', quantity: 50, unit: 'pcs', sku: 'HELM-EN397' },
      { id: 'line-2b', description: 'High-visibility vests XL', quantity: 80, unit: 'pcs' },
    ],
    supplierSelections: [
      { supplierId: 'sup-2', source: 'ARIAVEL', supplierNameSnapshot: 'SafeGuard Supplies', emailSnapshot: 'orders@safeguard.eu', selectedAt: '2026-09-02T11:00:00Z' },
      { supplierId: 'sup-3', source: 'ARIAVEL', supplierNameSnapshot: 'WorkWear Pro', supplierCodeSnapshot: 'WWP-007', selectedAt: '2026-09-02T11:30:00Z' },
    ],
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-02T11:30:00Z',
    createdByUserId: 'dev-user',
    updatedByUserId: 'dev-user',
  },
  {
    id: 'rfq-mock-3',
    tenantId: 'ariavel-development-tenant',
    reference: 'RFQ-2026-C3P7',
    title: 'IT Hardware & Peripherals',
    status: 'DRAFT',
    currency: 'USD',
    deadline: '2026-10-10',
    category: 'IT',
    ownerUserId: 'dev-user',
    ownerName: 'Dev User',
    lines: [
      { id: 'line-3a', description: 'USB-C Monitors 27"', quantity: 12, unit: 'pcs', targetUnitPrice: 350 },
    ],
    supplierSelections: [],
    createdAt: '2026-09-02T08:00:00Z',
    updatedAt: '2026-09-02T08:00:00Z',
    createdByUserId: 'dev-user',
    updatedByUserId: 'dev-user',
  },
];
